---
- name: Ensure Nginx is installed
  apt:
    name: nginx
    state: present
  become: yes

- name: Ensure Nginx service is running
  command: systemctl is-active nginx
  register: nginx_status
  failed_when: nginx_status.stdout != 'active'
  become: yes

- name: Ensure Nginx service is enabled
  command: systemctl is-enabled nginx
  register: nginx_enabled
  failed_when: nginx_enabled.stdout != 'enabled'
  become: yes

- name: Check if Nginx is listening on the correct port
  command: ss -tnlp | grep ':{{ nginx_port }}'
  register: nginx_port_check
  failed_when: nginx_port_check.rc != 0
  become: yes

- name: Verify Nginx is serving content on the port
  uri:
    url: "http://localhost:{{ nginx_port }}"
    status_code: 200
  register: nginx_test
  failed_when: nginx_test.status != 200