---
# tasks/main.yml
- name: Set correct permissions for Nginx configuration
  file:
    path: /etc/nginx/nginx.conf
    mode: '0644'
    owner: root
    group: root
  become: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: Copy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart Nginx
  become: yes

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: true
  become: yes

